version: "2.4"
services:
  vault:
    image: mterron/vault
    read_only: true
    restart: always
    ulimits:
      memlock: 9223372036854775807
    volumes:
      - /data
      - /etc/consul
      - /etc/vault
      - /etc/ssl/certs
      - ${PWD}/tls:/etc/tls
      - ${PWD}/config.json.template:/etc/vault/config.json.template
      - ${PWD}/consul.json.template:/etc/consul/consul.json.template
    tmpfs:
      - /tmp:noexec,mode=777
      - /run/consul:mode=770,size=1k,uid=100000,gid=100000
      - /home/vault:mode=700,uid=100001,gid=100001
    env_file: _env
    environment:
      - CONSUL_BOOTSTRAP_HOST
    dns:
      - 127.0.0.1
    dns_search:
      - service.consul
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - NET_BIND_SERVICE
      - SETUID
      - SETGID
      - IPC_LOCK
    ports:
      - 53
      - "53/udp"
      - 8200
      - 8300
      - 8301
      - "8301/udp"
      - 8302
      - "8302/udp"
      - 8501
